apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopub-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: index.docker.io/twerthi/octopub-frontend:2026.03.25.91
          ports:
            - containerPort: 8080
              name: frontend
