apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: octopub
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/twerthi/octopub-flux
  ref:
    branch: main
