apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-development-update-manifests-demo
  namespace: argocd
  annotations:
    argo.octopus.com/project: "update-manifests-demo"
    argo.octopus.com/environment: "development"  
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/octopub.git
    targetRevision: HEAD
    path: manifests/environments/development
  destination:
    server: https://kubernetes.default.svc
    namespace: development-update-manifests-demo
  syncPolicy:
#    automated: 
#      prune: true
#      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true