name: Package version test
permissions:
  contents: write
  packages: write
on:
  workflow_dispatch: # push:
  #   branches:
  #     - main

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create a release in Octopus Deploy 🐙
        id: create_a_release_in_octopus_deploy  
        uses: OctopusDeploy/create-release-action@v4
        with:
          project: 'Test slack'
          server: ${{ secrets.LOCAL_OCTOPUS_SERVER_URL }}
          api_key: ${{ secrets.LOCAL_OCTOPUS_API_KEY }}
          space: 'Default'
          packages: |
            Run a Script:accept_message.Azure.Function:20211117.3

      # - name: Deploy a release in Octopus Deploy 🐙
      #   id: deploy_a_release_in_octopus_deploy
      #   uses: OctopusDeploy/deploy-release-action@v4
      #   env:
      #     OCTOPUS_API_KEY: ${{ secrets.LOCAL_OCTOPUS_API_KEY }}
      #     OCTOPUS_URL: ${{ secrets.LOCAL_OCTOPUS_SERVER_URL }}
      #     OCTOPUS_SPACE: 'Default'
      #   with:
      #     project: 'Ephemeral Environments'
      #     release_number: ${{ steps.create_a_release_in_octopus_deploy.outputs.release_number }}
      #     environments: |
      #       ephemeral-environment-pr-${{ github.event.pull_request.number }}
